GET https://api.themoviedb.org/3/trending/tv/week?language=pt-BR
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIyNGFiYjczYjFlMjVjOTkzNTQ5ODE2ZmQ1NjM4MmQxMyIsIm5iZiI6MTc0MjE1MDU0NS4xMzUsInN1YiI6IjY3ZDcxYjkxNTc3NjY1YWNlNWYxYjRkOSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.Ztr9Fy2Oirex4lHE1ZHDcpuZRI8hPxuq5mmvoQ5OAG8